version: "3.9"
services:
  app:
    image: fdehech/devops:51 # Remplacez par votre image Docker
    ports:
      - "8081:8081" # Port pour accéder à l'application
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=devops
    depends_on:
      - db
      - sonarqube # S'assure que SonarQube est démarré
    networks:
      - my-network
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306" # Port pour MySQL
    networks:
      - my-network
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube-container
    ports:
      - "9000:9000" # Port pour accéder à l'interface SonarQube
    environment:
      - SONAR_JDBC_URL=jdbc:mysql://db:3306/devops?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance
      - SONAR_JDBC_USERNAME=root
      - SONAR_JDBC_PASSWORD=root
    depends_on:
      - db # S'assure que MySQL est démarré avant SonarQube
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
      - sonarqube-extensions:/opt/sonarqube/extensions
    networks:
      - my-network
volumes:
  mysql-data:
  sonarqube-data:
  sonarqube-logs:
  sonarqube-extensions:
networks:
  my-network:
    driver: bridge

