version: "3.9"
services:
  app:
    image: fdehech/devops:latest # Remplacez par votre image Docker
    ports:
      - "8080:8080" # Mappage des ports pour accéder à l'application
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=mydb
    depends_on:
      - db # S'assure que le conteneur 'db' démarre avant 'app'

  db:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306" # Mappage des ports pour accéder à la base de données

volumes:
  mysql-data: # Volume pour stocker les données de la base
